author = "Zeng Shu(Insilico Technologies, Inc.)"

baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "Node.js WebService"

theme = "hugo-theme-learn"

showVisitedLinks = false

# Disable search function. It will hide search bar
disableSearch = true

home = [ "HTML", "RSS", "JSON" ]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

 googlefonts = ["Droid Sans", "Fira Mono"]
 fontbody = 'Droid Sans'
 fontcode = 'Fira Mono'
 fontsizecode = 16
